server:
  servlet:
    context-path: /logsViabilizacion
  port: 5003

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.15:5432/samtel
    username: postgres
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: credito_consumo_acceso_datos_logs_viabilizacion_srv
    show-sql: true
    generate-ddl: false
  flyway:
    schemas: credito_consumo_acceso_datos_logs_viabilizacion_srv
    table: acceso_datos_logs_viabilizacion_flyway_schema_history
    locations: classpath:/db/migration
    baselineOnMigrate: true