
package org.tempuri;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WorkflowEngineSOA", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/C:/Users/jojmoreno/Documents/documentacion/samtel/viabilizacion/WorkflowEngineSOA.wsdl")
@HandlerChain(file="handler-chain.xml")
public class WorkflowEngineSOA
    extends Service
{

    private final static URL WORKFLOWENGINESOA_WSDL_LOCATION;
    private final static WebServiceException WORKFLOWENGINESOA_EXCEPTION;
    private final static QName WORKFLOWENGINESOA_QNAME = new QName("http://tempuri.org/", "WorkflowEngineSOA");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/jojmoreno/Documents/documentacion/samtel/viabilizacion/WorkflowEngineSOA.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WORKFLOWENGINESOA_WSDL_LOCATION = url;
        WORKFLOWENGINESOA_EXCEPTION = e;
    }

    public WorkflowEngineSOA() {
        super(__getWsdlLocation(), WORKFLOWENGINESOA_QNAME);
    }

    public WorkflowEngineSOA(WebServiceFeature... features) {
        super(__getWsdlLocation(), WORKFLOWENGINESOA_QNAME, features);
    }

    public WorkflowEngineSOA(URL wsdlLocation) {
        super(wsdlLocation, WORKFLOWENGINESOA_QNAME);
    }

    public WorkflowEngineSOA(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WORKFLOWENGINESOA_QNAME, features);
    }

    public WorkflowEngineSOA(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkflowEngineSOA(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WorkflowEngineSOASoap
     */
    @WebEndpoint(name = "WorkflowEngineSOASoap")
    public WorkflowEngineSOASoap getWorkflowEngineSOASoap() {
        return super.getPort(new QName("http://tempuri.org/", "WorkflowEngineSOASoap"), WorkflowEngineSOASoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WorkflowEngineSOASoap
     */
    @WebEndpoint(name = "WorkflowEngineSOASoap")
    public WorkflowEngineSOASoap getWorkflowEngineSOASoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WorkflowEngineSOASoap"), WorkflowEngineSOASoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WORKFLOWENGINESOA_EXCEPTION!= null) {
            throw WORKFLOWENGINESOA_EXCEPTION;
        }
        return WORKFLOWENGINESOA_WSDL_LOCATION;
    }

}
