server:
  servlet:
    context-path: /viabilizacion
  port: 5000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.15:5432/samtel
    username: postgres
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true


servicios:
  reconocerProperties:
    nit: 900468987
    tipoIdBuscar: 1
    numeroIdBuscar: 1010101010
    validarNombre: true
  ubicaProperties:
    codigoInformacion: 5632
    motivoConsulta: 1
  vigiaProperties:
    porcentaje: 76
  dictumProperties:
    codAliado: abcd
    usuarioAliado: alberto
    sessionId: 1234
    ipOrigen: 192.168.0.1
    numeroSolicitudCredito: 12345678
    tipoIdentificacion: CC
    identificacion: 1040

vigia:
  url: http://localhost:8080/vigia/
  service-name: vigia-service
validarciudad:
  url: http://localhost:5001/validacion/v1/
  service-name: validar-ciudad-service
dictum:
  url: http://localhost:8080/dictum/
  service-name: dictum-service
  parametros:
    clave: 06BRZ
    producto: 64
ubica:
  url:  http://localhost:8080/ubica/
  service-name: ubica-service
reconocer:
  url: http://localhost:8080/reconocer/
  service-name: ubica-service
bizagi:
  url: http://localhost:8080/bizagi/
  service-name: bizagi-service
viabilizacion:
  principal-request:
    url: http://localhost:5003/logsViabilizacion/v1/principalrequest
    service-name: viabilizacion-principal-request
  log:
    url: http://localhost:5003/logsViabilizacion/v1/logs
    service-name: viabilizacion-validar-ciudad
  servicio:
    url: http://localhost:5003/logsViabilizacion/v1/servicio
    service-name: viabilizacion-servicio

logging:
  level:
    co:
      com:
        santander:
          clients: DEBUG

