server:
  servlet:
    context-path: /viabilizacion
  port: 5000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://192.168.0.15:5432/samtel
    username: postgres
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true

servicios:
  uriValidarCiudad: http://localhost:5001/validacion/v1/ciudad/
  uriDictum: https://dictum.free.beeceptor.com/
  #uriDictum: http://dictum-credito-consumo-dev.apps.sv-bsnc-arquitectura-openshift.itac.com.co/consultarHC2
  reconocerProperties:
    uri: https://reconocer.free.beeceptor.com/
    #uri: http://reconocer-credito-consumo-dev.apps.sv-bsnc-arquitectura-openshift.itac.com.co/consultaReconocer
    uriToken: https://reconocer.free.beeceptor.com/obtenerToken
    #uriToken: http://reconocer-credito-consumo-dev.apps.sv-bsnc-arquitectura-openshift.itac.com.co/obtenerToken
    nit: 900468987
    tipoIdBuscar: 1
    numeroIdBuscar: 1010101010
    validarNombre: true
  ubicaProperties:
    uri: http://www.mocky.io/v2/5e492eae3000004a008c2cf7
    codigoInformacion: 5632
    motivoConsulta: 1
  vigiaProperties:
    uriVigia: https://vigia.free.beeceptor.com
    #uriVigia: http://vigia-credito-consumo-dev.apps.sv-bsnc-arquitectura-openshift.itac.com.co/consultaVigia
    porcentaje: 76

  dictumProperties:
    codAliado: abcd
    usuarioAliado: alberto
    sessionId: 1234
    ipOrigen: 192.168.0.1
    numeroSolicitudCredito: 12345678
    tipoIdentificacion: CC
    identificacion: 1040



dictum:
  parametros:
    clave: 06BRZ
    producto: 64