server:
  servlet:
    context-path: /viabilizacion
  port: 5000

servicios:
  reconocerProperties:
    nit: 900468987
    tipoIdBuscar: 1
    numeroIdBuscar: 1010101010
    validarNombre: true
  ubicaProperties:
    codigoInformacion: 5632
    motivoConsulta: 1
  vigiaProperties:
    porcentaje: 76
  dictumProperties:
    codAliado: abcd
    usuarioAliado: alberto
    sessionId: 1234
    ipOrigen: 192.168.0.1
    numeroSolicitudCredito: 12345678
    tipoIdentificacion: CC
    identificacion: 1040


dictum:
  parametros:
    clave: 06BRZ
    producto: 64



keycloak:
  client:
    service-name: keycloak
    url: https://sso-management-security.cloudapps.cosanpre.corp/auth/realms/3scale-api/protocol/openid-connect
    client-id: 3scale
    client-secret: e8bcd591-fa84-439c-804f-cd4e88f8246e
    grant-type: client_credentials