vigia:
  url: https://vigia.free.beeceptor.com
  service-name: vigia-service
validarciudad:
  url: http://localhost:5001/validacion/v1/
  service-name: validar-ciudad-service
dictum:
  url: https://dictum.free.beeceptor.com/
  service-name: dictum-service
ubica:
  url: https://ubica.free.beeceptor.com
  service-name: ubica-service
bizagi:
  url: http://localhost:5002/bizagi/v1/
  service-name: bizagi-service