server:
  servlet:
    context-path: /validacion
  port: 5001

spring:
  datasource:
    url: jdbc:h2:mem:samtel
    driverClassName: org.h2.Driver
    username: sa
    password: password
    main:
      allow-bean-definition-overriding: true
  flyway:
    schemas: public
    table: validar_ciudad_web_flyway_schema_history
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true

keycloak:
  realm: RealmSpringBoot
  auth-server-url: http://localhost:8080/auth
  resource: login
  principal-attribute: preferred_username
  public-client: true
  security-constraints[0]:
    auth-roles: user

