server:
  servlet:
    context-path: /validacion
  port: 5001

spring:
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.0.15:5432/samtel
      username: postgres
      password: 12345678
   flyway:
        schemas: public
        table: validar_ciudad_web_flyway_schema_history
        baseline-on-migrate: true
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      generate-ddl: true

keycloak:
  realm: RealmSpringBoot
  auth-server-url: http://localhost:8080/auth
  resource: login
  principal-attribute: preferred_username
  public-client: true