server:
  servlet:
    context-path: /validacion
  port: 5001

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/samtel
    username: postgres
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true

keycloak:
  realm: RealmSpringBoot
  auth-server-url: http://localhost:8080/auth
  resource: login
  principal-attribute: preferred_username
  public-client: true
  security-constraints[0]:
    auth-roles: user

