package co.com.santander.adapters.secondary.database.santander.constants;

public enum FlowOperationEnum {
	
	VALIDATE_CITY, VALIDATE_CITY_REQUEST, VALIDATE_CITY_RESPONSE,
	CHECK_LISTS, SEARCH_CACHE,
	INVOKE_DICTUM, INVOKE_DICTUM_REQUEST, INVOKE_DICTUM_RESPONSE,
	INVOKE_RECONOCER, INVOKE_RECONOCER_REQUEST, INVOKE_RECONOCER_RESPONSE,
	INVOKE_VIGIA, INVOKE_VIGIA_REQUEST, INVOKE_VIGIA_RESPONSE,
	INVOKE_UBICA,
	CASO_BIZAGI, CASO_BIZAGI_REQUEST, CASO_BIZAGI_RESPONSE,
	RESPONDER_PETICION,
	VALIDATE_CLIENT,
	NO_APLICA
	
}
