server:
  servlet:
    context-path: /validacion
  port: 5001
    
spring:
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/samtel
      username: postgres
      password: 12345678
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      generate-ddl: true