package co.com.santander.adapters.secondary.rest.informacioncontacto;

public class MockUbicaService {
    public static String response="{\n" +
            "\"codRespuesta\": 2,\n" +
            "\"respuestaServicio\": \"{\\\"CIFIN\\\":{\\\"archivo\\\":\\\"13022020182803417_90827_315439.xml\\\",\\\"Tercero\\\":{\\\"IdentificadorLinea\\\":49750353,\\\"RangoEdad\\\":\\\"25-30\\\",\\\"EstadoTitular\\\":\\\"\\\",\\\"CodigoMunicipio\\\":520,\\\"TipoIdentificacion\\\":\\\"C.C.\\\",\\\"CodigoCiiu\\\":\\\"\\\",\\\"RespuestaConsulta\\\":\\\"02\\\",\\\"NombreTitular\\\":\\\"PRUEBAS IDENTIFICACIO\\\",\\\"Estado\\\":\\\"VIGENTE\\\",\\\"LugarExpedicion\\\":\\\"PALMIRA\\\",\\\"Apellido1\\\":\\\"PRUEBAS\\\",\\\"Fecha\\\":\\\"13/02/2020\\\",\\\"Hora\\\":\\\"18:28:03\\\",\\\"Nombre1\\\":\\\"IDENTIFICACION\\\",\\\"UbicaPlusCifin\\\":{\\\"Mails\\\":{\\\"Mail\\\":{\\\"Correo\\\":\\\"LEO.STHEWAR.RINCON@GMAIL.COM\\\",\\\"NoReportes\\\":1,\\\"PrimerReporte\\\":\\\"14/06/12\\\",\\\"pos\\\":1,\\\"UltimoReporte\\\":\\\"14/06/12\\\"}},\\\"Celulares\\\":{\\\"Celular\\\":{\\\"NoReportes\\\":1,\\\"Celular\\\":3166492671,\\\"PrimerReporte\\\":\\\"14/06/12\\\",\\\"pos\\\":1,\\\"CelPos\\\":1,\\\"ProductoActivo\\\":\\\"NO\\\",\\\"UltimoReporte\\\":\\\"14/06/12\\\",\\\"SectorEconomico\\\":2}},\\\"Telefonos\\\":{\\\"Telefono\\\":{\\\"TelPos\\\":1,\\\"NoReportes\\\":1,\\\"Prefijo\\\":2,\\\"PrimerReporte\\\":\\\"14/06/12\\\",\\\"pos\\\":1,\\\"Telefono\\\":2611127,\\\"TipoUbicacion\\\":\\\"RES\\\",\\\"Ciudad\\\":\\\"PALMIRA ( VALLE )\\\",\\\"ProductoActivo\\\":\\\"NO\\\",\\\"UltimoReporte\\\":\\\"14/06/12\\\",\\\"SectorEconomico\\\":2}},\\\"GeneroTercero\\\":\\\"\\\"},\\\"NombreCiiu\\\":\\\"\\\",\\\"CodigoTipoIndentificacion\\\":1,\\\"FechaExpedicion\\\":\\\"26/01/2010\\\",\\\"CodigoDepartamento\\\":76,\\\"NumeroIdentificacion\\\":1113649731,\\\"NumeroInforme\\\":\\\"00003154390000316805\\\",\\\"Entidad\\\":\\\"EPRB PREMIER CREDIT\\\"}}}\",\n" +
            "\"mensajeError\": null\n" +
            "}";
}
