package com.samtel.domain.repository.entity;

public enum FlowOperationEnum {
	
	VALIDATE_CITY, VALIDATE_CITY_REQUEST, VALIDATE_CITY_RESPONSE,
	CHECK_LISTS, SEARCH_CACHE,
	INVOKE_DICTUM, INVOKE_DICTUM_REQUEST, INVOKE_DICTUM_RESPONSE,
	INVOKE_RECONOCER,
	INVOKE_VIGIA, INVOKE_VIGIA_REQUEST, INVOKE_VIGIA_RESPONSE,
	INVOKE_UBICA,
	CASO_BIZAGI,
	RESPONDER_PETICION,
	VALIDATE_CLIENT,
	NO_APLICA
	
}
