package com.samtel.domain.repository.entity;

public enum FlowOperationEnum {
	
	VALIDATE_CITY, CHECK_LISTS, SEARCH_CACHE, INVOKE_DICTUM, INVOKE_RECONOCER, INVOKE_VIGIA,
	INVOKE_UBICA, CASO_BIZAGI, RESPONDER_PETICION, VALIDATE_CLIENT, NO_APLICA
	
}
